# Generated by Django 5.1.7 on 2025-03-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_subject_professor_delete_professorsubject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(choices=[('university1', 'American University of Central Asia (AUCA)'), ('university2', 'American Institute of Technology (AIT)'), ('university3', 'Politech')], max_length=20, unique=True),
        ),
    ]
