# Generated by Django 5.1.7 on 2025-03-15 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_university_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='enrollment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='core.enrollment'),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(choices=[('university1', 'American University of Central Asia (AUCA)'), ('university2', 'American Institute of Technology (AIT)'), ('university3', 'Politech')], max_length=20, unique=True),
        ),
    ]
